### ISSUE TITLE
multiple broker it's a bit strange to use

### ISSUE THREAD

**Issue by josenspire** [eclipse/paho.mqtt.golang#464] opened 2020-11-10 08:39 UTC
**Background:**
- As we have 2 node but there is always only one node which will work normally, sometimes will happen to switch node.

**Event:**
- When i trying about the re-connection function. I found if i the first broker not working but second one is fine. Then connections will have a error about `Network Error : %!s(<nil>)`. Then you will get a empty client connection which means `isConnected()` is false. But if i convert the order of the two brokers that anything will work normally.
- That means the brokers must ensure that the first one must be valid.

**Comment by MattBrittan** [comment] 2020-11-11 02:36
Can you please enable logging (see the [readme](https://github.com/eclipse/paho.mqtt.golang)) and add the details from the log? I believe that this could happen when the TCP connection comes up but the response to the MQTT connect packet is not as expected.

I suspect that you are working with version `1.2.0`; looking at `@master` I don't see any obvious way that this message can be generated (there have been major changes since `1.2.0` including a rewrite of the connection code).

**Comment by MattBrittan** [comment] 2020-12-15 18:54
As there have been no updates on this in a month I'm going to close this issue. Version `1.3.0` has been released since my last comment; if you are still experiencing issues please try that and feel free to reopen this if the issue continues (please include debug logs - it seems likely that the problem is triggered by something specific to your environment).

**Closed by MattBrittan** 2020-12-15 18:54 UTC
