### ISSUE TITLE
Connection with invalid credentials can sometimes hang

### ISSUE THREAD

**Issue by ygbillet** [eclipse/paho.mqtt.golang#135] opened 2017-08-17 16:03 UTC
Hi, thanks to share this lib.

We try to connect using a bad password and some attempt seems to be handle as good credential : the return code is view as 0 instead of 4.

We think that sometimes this lib seems to miss packet.

We dig a bit and found that sometimes, value of [packetBytes ](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L115)in [ReadPacket()](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L101) is empty.
Then Value for msg.ReturnCode in [connect()](
https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L385) is 0.

Have you an idea on what happens ?

mqtt server: https://vernemq.com/
go version: go1.8.1 windows/amd64

**Comment by alsm** [comment] 2017-08-23 15:36
Thanks for reporting this, I'll take a look into it next week.

**Comment by alsm** [comment] 2017-09-08 15:47
I was unable to reproduce this issue myself, I've added a check in the ReadPacket() function that it is actually able to read as many bytes as it expects to from the RemainingLength and errors if the two are different. This won't return a not authorized error, because we were unable to confirm that, but will return non 0.
btw the expected error would be 5 - Not Authorised. 4 - Bad Username Or Password actually means that one or other of these fields contained data in format that could not be interpreted by the server, the naming is confusing. Please let me know if the change I've made resolves your issue.

**Comment by alsm** [comment] 2017-11-16 14:17
Closing as no update, if the issue persists please let me know.

**Closed by alsm** 2017-11-16 14:17 UTC
