### ISSUE TITLE
alllogic deadlock

### ISSUE THREAD

**Issue by dambrisco** [eclipse/paho.mqtt.golang#411] opened 2020-04-21 18:31 UTC
There appears to be some condition under which `alllogic` can become deadlocked. Attempts to publish messages from the client continue, but no net activity gets hit. The following logs are from a single programming talking to multiple brokers - broker addresses and topics have been scrubbed and the (repetitive) end of the log has been trimmed.

This is running of our fork (for enhanced logging capability) and has been seen with eclispe/paho.mqtt.golang master back to v1.2.0. We've been unable to document any method of reproduction so far.

Notable issues include that broker_b thrashes on connect frequently. Connections to a single, stable broker do not appear to present these issues. As much as I'm unable to identfy a cause in the code, it appears as though one `client` may pollute another.

Most relevant log snippet here: https://gist.github.com/dambrisco/4c6f4f032badbc3e88462503c88bd828
I can provide the full 51k line log from startup to failure if it's useful.

**Comment by MattBrittan** [comment] 2020-04-21 21:27
I believe the relevant log entry is most likely:

```
UTC 2020-04-21 15:31:54 [Debug] [broker: <scrubbed: broker_a>:1883] [is_connected: true] [is_connection_open: true] [net]     putting msg on onPubChan
```

There is no followup ```done``` entry so it looks like [```matchAndDispatch```](https://github.com/eclipse/paho.mqtt.golang/blob/master/router.go#L136) is blocked. This will prevent the ping response from being processed and also prevents the shutdown from completing ([```alllogic```](https://github.com/eclipse/paho.mqtt.golang/blob/master/net.go#L208) will not exit so we get stuck [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L549)).

As there is no logging in ```matchAndDispatch``` its not possible for me to lock this down further. However I suspect (based on past issues with my code!) that you have ```options.order``` set to ```true``` (the default) and the issue is in your message handler (if the handler does not return then everything locks up). I have seen this caused by a call to ```Publish``` from within a handler (if you do that then I suggest doing it in a go routine). My suggestion would be to add logging [here ](https://github.com/eclipse/paho.mqtt.golang/blob/master/router.go#L172) (or in your handler) to confirm if this is the case.

Unfortunately the interactions between the various go routines used within the mqtt package can make it hard to track this kind of thing down (I had a go at resolving this in #381).

**Comment by RobHumphris** [comment] 2020-04-22 07:32
We have exactly the same problem, occurring with only one Broker (Google's IoT MQTT Bridge), our application was running all night, until `05:02:11`
```
[DEBUG]    05:01:56 [pinger]   keepalive sending ping
[DEBUG]    05:02:01 [pinger]   ping check 4.999865254
[DEBUG]    05:02:06 [pinger]   ping check 9.999872009
[DEBUG]    05:02:11 [pinger]   ping check 14.99987396
[CRITICAL] 05:02:11 [pinger]   pingresp not received, disconnecting
[ERROR]    05:02:11 [net]      error triggered, stopping
[WARNING]  05:02:11 [net]      incoming dropped a received message during shutdown
[DEBUG]    05:01:56 [pinger]   keepalive sending ping
[DEBUG]    05:02:01 [pinger]   ping check 4.999865254
[DEBUG]    05:02:06 [pinger]   ping check 9.999872009
[DEBUG]    05:02:11 [pinger]   ping check 14.99987396
[CRITICAL] 05:02:11 [pinger]   pingresp not received, disconnecting
[ERROR]    05:02:11 [net]      error triggered, stopping
[WARNING]  05:02:11 [net]      incoming dropped a received message during shutdown
[DEBUG]    05:02:11 [net]      incoming stopped
[DEBUG]    05:02:11 [net]      outgoing stopped
```
Looking on Google's dashboard it tells us that they did receive the ping, and seeing that they sent the Config 14 seconds later believed that they were in communication at `05:02:11` as they sent a Config. message
![image](https://user-images.githubusercontent.com/220434/79952772-d8ffc380-8472-11ea-8ee4-2c777fe313ae.png)
Google say: `Config. sent 05:02:11` and our application reports: `05:02:11 [net]      incoming dropped a received message during shutdown` so there is still a connection between client and broker.

Because the connection is not properly closed the application attempts to publish to a dead connection: 
```
[DEBUG]    05:07:52 [client]   enter Publish
[DEBUG]    05:07:52 [client]   sending publish message, topic: /devices/pc-rob-desktop/events
```
Which leaves the application deadlocked (I had written a work around, but removed it to see exactly what was going on).
Attempting to run `client.Disconnect` at this point also causes a deadlock.

**Comment by MattBrittan** [comment] 2020-04-23 04:17
@RobHumphris do you also see a ```putting msg on onPubChan``` without a matching ```done putting msg on incomingPubChan``` in your log (I would expect this to be above ```keepalive sending ping```)? Your symptoms do appear to be the same; as you also have no ```logic stopped``` in your log it looks like [alllogic](https://github.com/eclipse/paho.mqtt.golang/blob/master/net.go#L208) is deadlocked. As I mentioned in my previous post I have seen this before where a message handler (as set in a call to ```Subscribe```, ```AddRoute``` or via ```options.DefaultPublishHandler```) does not return (perhaps because it attempts to publish a message) so that is what I would checking for that first.

**Comment by RobHumphris** [comment] 2020-04-23 06:44
@MattBrittan Yes.
```
[DEBUG]    19:18:27 [net]      putting msg on onPubChan
[DEBUG]    19:18:30 [pinger]   ping check 24.977473351
[DEBUG]    19:18:35 [pinger]   ping check 29.977449572
[DEBUG]    19:18:37 [net]      Received Message
[DEBUG]    19:18:40 [pinger]   ping check 34.97717129
[DEBUG]    19:18:40 [pinger]   keepalive sending ping
[DEBUG]    19:18:45 [pinger]   ping check 4.999951364
[DEBUG]    19:18:50 [pinger]   ping check 10.0002054
[CRITICAL] 19:18:50 [pinger]   pingresp not received, disconnecting
[ERROR]    19:18:50 [net]      error triggered, stopping
[DEBUG]    19:18:50 [net]      outgoing stopped
[WARNING]  19:18:50 [net]      incoming dropped a received message during shutdown
[DEBUG]    19:18:50 [net]      incoming stopped
```

**Comment by MattBrittan** [comment] 2020-05-04 08:22
PR #381 has now been committed and this significantly changes the way the various go routines interact; one of the aims was to remove potential deadlocks. Can you please give this a go (```go get  github.com/eclipse/paho.mqtt.golang@master```) a go and see if this resolves the issues you have been experiencing (note that as this is quite a major change that has just been committed I'd suggest deploying to test first!). If the issues do continue please uncomment the logging in ```router.go``` (e.g. ```DEBUG.Println(ROU, "matchAndDispatch received message")```) and, ideally add additional logging around the call to ```handler(client, m)``` at the end.

**Comment by RobHumphris** [comment] 2020-05-04 09:39
Thanks for your efforts on this. We're putting the latest on our test rig this morning.

**Comment by MattBrittan** [comment] 2020-05-30 02:22
Hi @RobHumphris & @dambrisco; Just wondering if the new version has resolved this issue for you?

**Comment by RobHumphris** [comment] 2020-05-30 10:38
We had issues with re-connection almost immediately, as we're using GSM for telemetry we needed something that allowed us to establish when comms had dropped out so I ended up writing a very minimal client that exposed the Ping-Pong traffic via a channel.

**Comment by MattBrittan** [comment] 2020-05-30 21:33
Thanks @RobHumphris - do you think the issue may have been #419? (understand that you are no longer using this but keen to fix this issue if it's still there).

**Comment by dambrisco** [comment] 2020-06-01 23:12
@MattBrittan We'll get a build out with the latest in the next day or two and put it through the motions. We pulled an older version and patched both it and our own code (thanks to you pointing us to the handlers) and things have been fine since, but we don't like to fall too far behind current versions.

**Comment by MattBrittan** [comment] 2020-12-07 19:54
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.

**Closed by MattBrittan** 2020-12-07 19:54 UTC
