### ISSUE TITLE
Connected while return code is `not authorized`

### ISSUE THREAD

**Issue by m-manns** [eclipse/paho.mqtt.golang#243] opened 2018-10-19 08:39 UTC
* Paho Version: v1.1.1
* Code to reproduce the issue
```go
package main

import (
	"flag"
	"fmt"
	"time"

	MqttLib "github.com/eclipse/paho.mqtt.golang"
	log "github.com/sirupsen/logrus"
)

func main() {
	log.SetLevel(log.DebugLevel)
	log.Info("Client MQTT...")

	flagIP := flag.String("ip", "", "IP MQTT broker")
	flagPort := flag.String("port", "1883", "Port MQTT")
	flagUser := flag.String("username", "", "MQTT username")
	flagPass := flag.String("password", "", "MQTT password")
	flag.Parse()

	url := fmt.Sprintf("tcp://%v:%v", *flagIP, *flagPort)

	options := MqttLib.NewClientOptions().AddBroker(url)
	options.SetConnectionLostHandler(func(lost MqttLib.Client, err error) {
		log.WithFields(log.Fields{
			"error": err,
		}).Error("Connection to MQTT broker lost")
	})
	options.SetClientID(*flagUser)
	options.SetUsername(*flagUser)
	options.SetPassword(*flagPass)
	options.AutoReconnect = true
	options.OnConnect = func(c MqttLib.Client) {
		log.Info("Connected to MQTT broker")
	}

	client := MqttLib.NewClient(options)
	token := client.Connect()
	if token.Wait() && token.Error() != nil {
		log.WithFields(log.Fields{
			"error": token.Error(),
			"url":   url,
		}).Error("MQTT server connection error")
	} else {
		log.WithFields(log.Fields{
			"url": url,
		}).Debug("MQTT server connection")
	}

	log.WithFields(log.Fields{
		"is connected": client.IsConnected(),
	}).Info("Connection status")

	if client.IsConnected() {
		client.Disconnect(1)
	}
	time.Sleep(time.Duration(2) * time.Second)
}
```

# Description

A MQTT client attempts to connect to a broker with bad password. The Paho library does not wait for the return code and considers the client as connected. But when we check network frames (with Wireshark), we can see `Connect Ack` frame with return code `not authorized (5)` (as you can see in this screenchot).

![wireshark](https://user-images.githubusercontent.com/32070871/47207216-f1c57f80-d38a-11e8-89ae-cda1aa57cb1a.png)

Logs of example client in this situation:

```
INFO[0000] Client MQTT...
INFO[0000] Connected to MQTT broker
DEBU[0000] MQTT server connection                        url="tcp://192.168.1.82:1883"
INFO[0000] Connection status                             is connected=true
ERRO[0000] Connection to MQTT broker lost                error="read tcp 192.168.1.90:31910->192.168.1.82:1883: wsarecv: Une connexion existante a dû être fermée par l’hôte distant."
```

Sometimes connection is normally refused. In most cases, it is accepted with the wrong password.

**Comment by odedva** [comment] 2018-10-20 08:56
Have you tried using the isConnectionOpen method for that ? was merged just 10 days ago.
https://github.com/eclipse/paho.mqtt.golang/pull/217/commits/4ca402388bdb35452d682284125a15c0c3feb16b

**Comment by alsm** [comment] 2018-10-25 16:13
This was not quite as intended, it's meant to hide blips in connectivity while reconnecting, but unfortunately means that it returned true as soon as you started a connection, even if the details you gave to connect with would never work. I've just made a change to only do this after having connected successfully

**Closed** 2018-10-25 16:13 UTC

**Comment by m-manns** [comment] 2018-10-26 07:11
Thank you for your answers to both of you!!

Problem is solved with new commits.
