### ISSUE TITLE
Telegraf+MQTT panic: runtime error: invalid memory address 

### ISSUE THREAD

**Issue by dogada** [eclipse/paho.mqtt.golang#341] opened 2019-07-19 11:30 UTC
Started to observe this error when traffic to MQTT-server is increased to 3000 packets/secods (with 500 packets/seconds it worked fine).

Please see more info at: https://github.com/influxdata/telegraf/issues/6142

```
telegraf_1    | panic: runtime error: invalid memory address or nil pointer dereference
telegraf_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1247983]
telegraf_1    | 
telegraf_1    | goroutine 70 [running]:
telegraf_1    | github.com/influxdata/telegraf/vendor/github.com/eclipse/paho%2emqtt%2egolang.outgoing(0xc000090700)
telegraf_1    |         /go/src/github.com/influxdata/telegraf/vendor/github.com/eclipse/paho.mqtt.golang/net.go:202 +0xb33
telegraf_1    | created by github.com/influxdata/telegraf/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
telegraf_1    |         /go/src/github.com/influxdata/telegraf/vendor/github.com/eclipse/paho.mqtt.golang/client.go:295 +0x6e7
```

**Comment by MattBrittan** [comment] 2019-07-19 23:08
I believe this is a duplicate of #226 which was fixed in PR https://github.com/eclipse/paho.mqtt.golang/pull/239. From the Gopkg.lock in the telegraf repo it looks like version 1.1.1 of this package is in use; I'd suggest upgrading to version 1.2 which includes the fix.

**Comment by dogada** [comment] 2019-07-20 21:17
Thanks @matiasinsaurralde, I asked Telegraf team to upgrade.

**Comment by MattBrittan** [comment] 2020-12-07 19:23
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.

**Closed by MattBrittan** 2020-12-07 19:23 UTC
