### ISSUE TITLE
how to upload data by the specified network interface

### ISSUE THREAD

**Issue by jerryzhengj** [eclipse/paho.mqtt.golang#553] opened 2021-10-21 08:13 UTC
There are two network interfaces in my linux host. one is eth0, the other is eth1.
      As mqtt client，I want to send msg to mqtt broker through eth1.

      How to configure network interface when creating mqtt connection ?

**Comment by MattBrittan** [comment] 2021-10-21 08:38
This library uses the standard go libraries for [network access]((https://github.com/eclipse/paho.mqtt.golang/blob/master/netconn.go#L51); how traffic is routed depends upon the setup of your TCP stack (and how you configure this depends upon your OS). As this is a general networking question and [not a bug report](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) I'm going to close it; I'd suggest asking at a site like [superuser](https://superuser.com).

**Closed by MattBrittan** 2021-10-21 08:38 UTC
